name: Update Rewards

# Trigger the workflow every hour
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-rewards:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch rewards data
      run: |
        # Fetch the rewards data using curl or wget
        curl "https://api.allorigins.win/get?url=http%3A%2F%2Fsimnationserver.com%2Fredeem%2F" > rewards.json

    - name: Commit updated rewards data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add rewards.json
        git commit -m "Updated rewards data"
        git push
